---
title: "hw5_xw2598"
author: "Xinyao Wu"
date: "2018/11/4"
output: github_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
```

##Problem 1

*tidy data
```{r tidy_data}
#a dataframe containing all file names
file_ls =tibble(
  path = list.files("data/")
  )
#function:read data
read_data = function(x){
  path = str_c("data/",x)
  file = read.csv(path)
  file
}
#combine data
file = file_ls %>% 
mutate(map(file_ls$path,read_data)) %>% 
  unnest() %>% 
  #separate path name 
  separate(path,into = c("group","subject_Id"), sep = "_") %>% 
  #tidy path name
  mutate(
    subject_Id = str_replace(subject_Id,".csv", " "),
    group = as.factor(group)
      ) %>% 
  #tidy data
 gather(key = "week", value = value, week_1:week_8) %>% 
  mutate(
    week = as.factor(str_replace(week,"week_", " "))
  ) 
```
*make a plot
```{r make_plots}
file %>% 
ggplot(aes(x = week, y = value, group= subject_Id,color = subject_Id))+
  geom_line()+
  facet_grid(~group)+
 
  labs(
    y = "Observation value",
    color = "Subject Id",
    title = "Observation value change tendency from control and experimental subjects "
  )

```

####Comments:
The observation value change from control group are more static than the experimental group, the latter has an obvious increasing tendency over time.

##Problem2
*read and clean data
```{r collapse=TRUE,warning=FALSE}
wp_df = read.csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
janitor::clean_names() %>% 
  mutate(city_state = str_c(city,state,sep = ","))

#date range 
pull(wp_df,reported_date) %>%
  as.character() %>% 
  range()
#victim age range
pull(wp_df,victim_age) %>%as.character() %>% as.integer() %>% range(na.rm =TRUE)
```
####Describe the raw data:


```{r}
#calculated the total number of homicides and unsolved homicides
homicide = wp_df %>% 
  group_by(city_state) %>% 
  mutate(
    unsolved = ifelse(disposition == "Closed by arrest",0,1)
      ) %>% 
  summarise(
    total_homicides = n(),
    unsolved_homicides = sum(unsolved)
  ) 
homicide
```
####comments


```{r  collapse = TRUE}
 balti = homicide  %>% 
#select the city of Baltimore,MD
  filter(city_state == "Baltimore,MD") 
#using prop.test function 
balti = prop.test(balti$unsolved_homicides, balti$total_homicides) 
#turn the outcome into a tidy tribble
balti = broom::tidy(balti)  
#pull the estimated proportion and
pull(balti,estimate)
#confidence intervals
#low limit
pull(balti,conf.low)
#high limit
pull(balti,conf.high)
```

```{r warning=FALSE}
prop_df = homicide %>% 
  mutate(
    test = map2(.x = unsolved_homicides, .y = total_homicides, prop.test),
    test = map(test,broom::tidy)
         )  %>% 
  unnest() %>% 
  select(city_state, estimate, conf.low, conf.high) 
prop_df
```
###comments

```{r plot}
prop_df %>% 
  ggplot(aes(x = reorder(city_state,estimate), y =estimate))+
  geom_point()+
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high))+
  theme(
    axis.text.x = element_text(angle = 90,hjust = 1,size = 6.5)
  )+
  labs(
    title = "The proportions of unsolved homicides in some US cities",
    y = "Proportion of unsolved homicides",
    x = "City",
    caption = "Data from Washington post"
  )
```

####Comments




























